config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recommendations#index"
  resources :users, only: :show
  resources :recommendations, only: %i[index show]
  post "recommendation_favorite" => "recommendations#create_from_favorites", as: :recommendation_favorite
  post "recommendation_list/:id" => "recommendations#create_from_list", as: :recommendation_list

  resources :lists, only: %i[show create]
  resources :movies, only: %i[index create] do
    resources :list_movies, only: %i[create]
    resources :favorites, only: %i[create]
  end
  resources :favorites, only: %i[index create destroy]
  resources :watched_movies, only: %i[index create]
  resources :watch_later, only: %i[index]

  get "user/lists" => "lists#index", as: :user_lists
  get "user/lists/:id/edit" => "lists#edit", as: :user_list_edit
  patch "lists/:id" => "lists#update", as: :settings_list_update
  delete "user/lists/:id" => "lists#destroy", as: :user_list_destroy

  resources :chatrooms do
    resources :messages, only: :create
  end
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_movies, dependent: :destroy
  has_many :movies, through: :list_movies, source: :movie

  validates :name, presence: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.where(user: current_user).order(updated_at: :desc)
    @list = List.new
  end

  def show
    @lists = List.where(user: current_user)
    @list = List.find(params[:id])
    if params[:search]
      @movies = ListMovie.where(list: @list).where("title ILIKE ?", "%#{params[:search]}%").page(params[:page]).per(20)
     # @list_movies = @list.movies.where("title ILIKE ?", "%#{params[:search]}%").page(params[:page]).per(20)
    else
      #@list_movies = @list.movies.page(params[:page]).per(20)
      @list_movies = ListMovie.where(list: @list).page(params[:page]).per(20)
    end
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    respond_to do |format|
      if @list.save!
        format.html { redirect_to list_path(@list) }
        format.json # Follows the classic Rails flow and look for a create.json view
      else
        format.html { render "settings/lists", status: :unprocessable_entity }
        format.json # Follows the classic Rails flow and look for a create.json view
      end
    end
  end

  def edit
    @list = List.find(params[:id])
    @lists_sidebar = List.where(user: current_user).order(updated_at: :desc).first(5)
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to user_lists_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to user_lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end


end

app/views/lists/_form.html.erb
<%= simple_form_for(list, html: { data: {
      insert_in_the_list_target: 'form',
      action: "submit->insert-in-the-list#send"
    } } ) do |f| %>
  <div data-display-form-target="form" class="d-none">
    <%= f.input :name, label: "List name" %>
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lists/_list.html.erb
<div class="col-6 my-3">
  <div class="d-flex align-items-center justify-content-between bg-secondary p-3 rounded">
    <%= link_to list.name, list, class: "nav-link text-white" %>
    <div class="d-flex align-items-center gap-3">
      <span class="badge text-bg-secondary"><%= list.movies.count %> movies in</span>
      <%= link_to user_list_edit_path(list), class: "text-white" do %>
        <i class="fas fa-edit"></i>
      <% end %>
      <%= link_to user_list_destroy_path(list), class: "text-danger",
      data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure you want to delete #{list.name}?"
      } do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<h1 class="text-center my-3">Your profile</h1>

<div class="row w-75 mx-auto">
  <h2 class="text-center">Edit the <%= @list.name %></h2>
  <div class="col-8 mx-auto mt-3">
    <%= simple_form_for(@list) do |f| %>
      <%= f.input :name, label: "List name" %>
      <%= f.button :submit, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/lists/index.html.erb
<h1 class="text-center my-3">Your profile</h1>

<h2 class="text-center">Your lists</h2>
<div class="row w-75 mx-auto" data-controller="insert-in-the-list">
  <div data-controller="display-form">
    <button class="btn btn-primary" data-action="click->display-form#toggle">Create a new list</button>
    <div>
      <%= simple_form_for(@list, html: { data: { 
            insert_in_the_list_target: 'form',
            action: "submit->insert-in-the-list#send"
          } } ) do |f| %>
        <div data-display-form-target="form" class="d-none">
          <%= f.input :name, label: "List name" %>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row" data-insert-in-the-list-target="items">
    <% @lists.each do |list| %>
      <%= render "lists/list", list: list %>
    <% end %>
  </div>
</div>

app/views/lists/show.html.erb
<% @hero_movies = [
      { poster_url: "https://media1.ledevoir.com/images_galerie/nwd_230771_163004/image.jpg", title: "Mommy (2014)" },
      { poster_url: "https://www.hollywoodreporter.com/wp-content/uploads/2022/03/MCDGODF_EC002.jpg?w=2000&h=1126&crop=1", title: "Godfather (1972)" },
      { poster_url: "https://media.newyorker.com/photos/59097b4a8b51cf59fc423bff/16:9/w_1280,c_limit/Tolentino-Handmaiden.jpg", title: "Handmaiden (2016)" }
    ]
    index = rand(0..2)
%>

<%= render "layouts/page_list", ai_reco: true, reco_path: recommendation_list_path(@list), search_on: favorites_path, title: @list.name, image_url: @hero_movies[index][:poster_url], movie_title: @hero_movies[index][:title], movie_rating: "8.0", section: "lists", search_on: list_path(@list) %>

<div class="container-section d-flex flex-column flex-wrap">
  <div class="row">
  <% if !@list_movies.nil? %>
  <% @list_movies.each do |list_movie| %>
    <%= render "movies/movie", movie: list_movie.movie, carousel:false, bs_class: "col-sm-6 col-md-6 col-lg-3 col-xl-2 my-2 text-wrap text-center" %>
  <% end %>
<% else %>
  <p>No movie in this list yet</p>
<% end %>
  </div>
</div>