config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recommendations#index"
  resources :users, only: :show
  resources :recommendations, only: %i[index show]
  post "recommendation_favorite" => "recommendations#create_from_favorites", as: :recommendation_favorite
  post "recommendation_list/:id" => "recommendations#create_from_list", as: :recommendation_list

  resources :lists, only: %i[show create]
  resources :movies, only: %i[index create] do
    resources :list_movies, only: %i[create]
    resources :favorites, only: %i[create]
  end
  resources :favorites, only: %i[index create destroy]
  resources :watched_movies, only: %i[index create]
  resources :watch_later, only: %i[index]

  get "user/lists" => "lists#index", as: :user_lists
  get "user/lists/:id/edit" => "lists#edit", as: :user_list_edit
  patch "lists/:id" => "lists#update", as: :settings_list_update
  delete "user/lists/:id" => "lists#destroy", as: :user_list_destroy

  resources :chatrooms do
    resources :messages, only: :create
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
    if params[:search]
      @favorites = Favorite.where(user: current_user).joins(:movie).where('title ILIKE ?', "%#{params[:search]}%")
    else
      @favorites = Favorite.where(user: current_user)
    end
  end

  def create
    @movie = Movie.find(params[:movie_id])
    # @favorite = Favorite.find_or_initialize_by(movie: @movie, user: current_user)

    @favorite = Favorite.find_by(movie: @movie, user: current_user)

    if @favorite
      @favorite.destroy
      render json: { status: 'success', message: 'Movie removed from favorites' }, status: :ok
    else
      @favorite = Favorite.create(movie: @movie, user: current_user)
      render json: { status: 'success', message: 'Movie added to favorites' }, status: :ok
    end
  end
end

app/views/favorites/index.html.erb
<%=  render "layouts/page", ai_reco: true, reco_path: recommendation_favorite_path, search_on: favorites_path, title: "Favorites", image_url: "https://m.media-amazon.com/images/S/pv-target-images/85f996deb6e03425868a24a26eacccc0aa96e9c6dfe835a2e54d35776e046949.jpg", movie_title: "The Wolf of Wall Street", movie_rating: "8.2", section: "favourites"%>

<div class="container-section d-flex flex-column flex-wrap">
  <div class="row my-4">
    <% if !@favorites.empty? %>
      <% @favorites.each do |favorite| %>
        <%= render "movies/movie", movie: favorite.movie, section: "favorites", lists: @lists_sidebar, carousel: false, bs_class: "text-wrap text-center" %>
      <% end %>
    <% else %>
      <p>No favorites yet</p>
    <% end %>
  </div>
</div>