config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recommendations#index"
  resources :users, only: :show
  resources :recommendations, only: %i[index show]
  post "recommendation_favorite" => "recommendations#create_from_favorites", as: :recommendation_favorite
  post "recommendation_list/:id" => "recommendations#create_from_list", as: :recommendation_list

  resources :lists, only: %i[show create]
  resources :movies, only: %i[index create] do
    resources :list_movies, only: %i[create]
    resources :favorites, only: %i[create]
  end
  resources :favorites, only: %i[index create destroy]
  resources :watched_movies, only: %i[index create]
  resources :watch_later, only: %i[index]

  get "user/lists" => "lists#index", as: :user_lists
  get "user/lists/:id/edit" => "lists#edit", as: :user_list_edit
  patch "lists/:id" => "lists#update", as: :settings_list_update
  delete "user/lists/:id" => "lists#destroy", as: :user_list_destroy

  resources :chatrooms do
    resources :messages, only: :create
  end
end

app/controllers/recommendations_controller.rb
require 'dotenv/load'
require 'net/http'
require 'json'
require 'openai'

class RecommendationsController < ApplicationController
  before_action :load_user_data, only: [:index, :show]
  def index
    if params[:query].present?
      gpt_query = GptQuery.create(query: params[:query], user: current_user)
      redirect_to recommendation_path(gpt_query)
    else
      load_user_data
    end
  end

  def create_from_favorites
    gpt_query = GptQuery.create(query: "favorites", user: current_user)
    redirect_to recommendation_path(gpt_query)
  end

  def create_from_list
    list = List.find(params[:id])
    list_ids = list.movies.map(&:imdb_id).join(", ")
    gpt_query = GptQuery.create(query: list_ids, user: current_user)
    redirect_to recommendation_path(gpt_query)
  end

  def show
    @gpt_query = GptQuery.find(params[:id])
    @movies = @gpt_query.movies
  end

  private

  def load_user_data
    @queries = GptQuery.where(user: current_user).to_a.reject { |query| query.query.include?("favorites") || query.query.match?(/tt\d*/) }
    @movies = current_user.query_movies.to_a.map { |query| Movie.find(query.movie_id) }.uniq
    @favorites = Favorite.where(user: current_user).to_a.map(&:movie)
    @lists = List.where(user: current_user).order(updated_at: :asc)
  end
end

app/views/recommendations/_arrow.html.erb
<svg width="17" height="33" viewBox="0 0 17 33" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M1 31.5834L15 16.4584L1 1.33337" stroke="white" stroke-width="2"/>
</svg>

app/views/recommendations/_card_result.html.erb
<% if !movie.poster_url.blank? %>
<div class="col-6 my-4">
  <div class="card-result">
    <%= render "movies/movie", movie: movie, section: "", lists:current_user.lists, carousel: false , bs_class: "col-5" %>
    <div class="card-result__info">
      <h3 class="card-result__info__title"><%= movie.title %></h3>

      <%# <div class="card-result__info__quote"><%= query.reco_title %>
      <p class="card-result__info__description"><%= query.reco_description %></p>
    </div>
  </div>
</div>
<% end %>

app/views/recommendations/_section.html.erb
 <section class="container px-4 special">
      <h2>Special for you</h2>
      <div data-controller="carousel" class="carousel">
        <div class="siema" data-carousel-target="siema">
          <% @movies.each do |movie| %>
            <div class="siema-slide">
              <%= render "movies/movie", movie: movie, section: "recommendations", lists: @lists_sidebar, carousel: true, bs_class: "col-sm-6 col-md-6 col-lg-3 col-xl-2 my-2 text-wrap text-center" %>
            </div>
          <% end %>
        </div>
        <button class="prev" data-action="click->carousel#prev">
          <%= render 'arrow' %>
        </button>
        <button class="next" data-action="click->carousel#next">
          <%= render 'arrow' %>
        </button>
      </div>
</section>

app/views/recommendations/index.html.erb
<div class="container-grid">
  <div class="container-grid__header hero" data-controller="hero-changer" data-hero-changer-target="hero" style="background-image: linear-gradient(to bottom, rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3) 70%, rgba(255, 255, 255, 1) 100%), url('https://exitmag.fr/wp-content/uploads/sites/21/2024/04/The-Fall-Guy-1-Ryan-Gosling.webp');">
    <div class="search-box d-flex flex-column">
      <h2>The best AI movie search engine</h2>
          <h3>Tired of searching 3 hours for a movie idea?</h3>

        <%= form_with url: recommendations_path, method: :get, class: "d-flex search-form my-4", data: { controller: "prompt" } do |form| %>
  <%= form.text_field :query, value: params[:query], class: "search-input", placeholder: "", data: { prompt_target: "input" } %>

            <%= button_tag(type: 'submit', name: '', class: 'search-button', data: { action: "click->prompt#displayLoader" }) do %>
              <div class="d-flex align-items-center"><%= render 'layouts/icon' %><span class="ms-2">Search</span></div>
            <% end %>
          <% end %>
          <% if @queries && !@queries.empty? %>
            <h4 class="mt-4">Your last searches</h4>
            <div class="buttons d-flex">
              <% @queries.last(3).reverse.each do |query| %>
                <button class="d-flex justify-content-between align-items-center">
                  <small class="me-2"><%= query.query %></small><span class="d-flex justify-content-center align-items-center"><i class="fas fa-times"></i></span>
                </button>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%# <div data-controller="siema"> %>
    <%# <% @queries.each do |query| %>
      <%# <%= render 'section', query: query %>
      <%# </div>  %>
      <section class="special">
        <h2 class="mb-3">Special for you</h2>
        <div data-controller="carousel" class="carousel">
          <div class="siema" data-carousel-target="siema">
            <% @movies.sample(10).each do |movie| %>
              <div class="siema-slide">
                <% unless movie.poster_url == "N/A" || movie.poster_url.nil? || movie.poster_url.empty? %>
                  <%= render "movies/movie", movie: movie, section: "recommendations", lists: @lists_sidebar, carousel: true, bs_class: "" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <!--<button class="prev" data-action="click->carousel#prev">
            <%#= render 'arrow' %>
          </button>
          <button class="next" data-action="click->carousel#next">
            <%#= render 'arrow' %>
          </button>-->
        </div>
      </section>
      <section class="my-4">
        <h2>Your favorites</h2>
        <div data-controller="carousel" class="carousel">
          <div class="siema" data-carousel-target="siema">
            <% @favorites.sample(10).each do |movie| %>
              <div class="siema-slide">
                <%= render "movies/movie", movie: movie, section: "recommendations", lists: @lists_sidebar, carousel: true, bs_class: "col-sm-6 col-md-6 col-lg-3" %>
              </div>
            <% end %>
          </div>
          <button class="prev" data-action="click->carousel#prev">
            <%= render 'arrow' %>
          </button>
          <button class="next" data-action="click->carousel#next">
            <%= render 'arrow' %>
          </button>
        </div>
      </section>

app/views/recommendations/show.html.erb
<div class="container px-5">
  <div class="d-flex justify-content-between w-100 align-items-center my-5">
    <h2 class=""><i><%= @gpt_query.query.match?(/ttd*/) ? "Recommended from your list" : "Results for #{@gpt_query.query}" %></i></h2>
    <%= link_to 'Back to Home', root_path, class: 'btn btn-primary mb-3' %>
  </div>
  <section class="container">
    <div class="row">
      <% @gpt_query.query_movies.each do |query_movie| %>
        <%= render "recommendations/card_result", movie: query_movie.movie, query: query_movie %>
      <% end %>
    </div>
  </section>
</div>