config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "recommendations#index"
  resources :users, only: :show
  resources :recommendations, only: %i[index show]
  post "recommendation_favorite" => "recommendations#create_from_favorites", as: :recommendation_favorite
  post "recommendation_list/:id" => "recommendations#create_from_list", as: :recommendation_list

  resources :lists, only: %i[show create]
  resources :movies, only: %i[index create] do
    resources :list_movies, only: %i[create]
    resources :favorites, only: %i[create]
  end
  resources :favorites, only: %i[index create destroy]
  resources :watched_movies, only: %i[index create]
  resources :watch_later, only: %i[index]

  get "user/lists" => "lists#index", as: :user_lists
  get "user/lists/:id/edit" => "lists#edit", as: :user_list_edit
  patch "lists/:id" => "lists#update", as: :settings_list_update
  delete "user/lists/:id" => "lists#destroy", as: :user_list_destroy

  resources :chatrooms do
    resources :messages, only: :create
  end
end

app/views/shared/_dark_mode_toggle.html.erb
<div data-controller="dark-mode">
  <input type="checkbox" class="checkbox" id="checkbox" data-action="click->dark-mode#toggle" data-dark-mode-target="checkbox">
  <label for="checkbox" class="checkbox-label">
    <span class="ball d-flex justify-content-center align-items-center">
      <i class="fas fa-moon"></i>
    </span>
  </label>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_logo.html.erb
<svg width="146" height="23" viewBox="0 0 146 23" fill="none" xmlns="http://www.w3.org/2000/svg" class="logo">
<path d="M17.469 5.8L12.528 22H4.61701L0.13501 5.8H5.45401L8.66701 18.22H8.82901L12.366 5.8H17.469Z"/>
<path d="M19.3683 5.8H24.4983V22H19.3683V5.8ZM19.2333 4.18V0.400002H24.6333V4.18H19.2333Z"/>
<path d="M43.636 0.400002V22H38.641V18.625C38.182 21.19 36.535 22.324 33.376 22.324C28.327 22.324 27.058 20.65 27.058 13.9C27.058 7.15 28.273 5.476 33.106 5.476C36.184 5.476 37.912 6.232 38.506 7.987V0.400002H43.636ZM32.458 13.9C32.458 17.599 32.755 18.004 35.536 18.004C37.399 18.004 38.506 17.491 38.506 16.276V12.874C38.506 10.714 37.534 9.796 35.239 9.796C32.728 9.796 32.458 10.201 32.458 13.9Z"/>
<path d="M62.4101 16.843C62.3021 21.217 60.6821 22.324 54.3101 22.324C47.7221 22.324 46.0751 20.65 46.0751 13.9C46.0751 7.15 47.7221 5.476 54.3101 5.476C60.7091 5.476 62.4101 6.961 62.5451 12.847V15.358H51.5021C51.6101 18.193 52.1231 18.544 54.3371 18.544C56.4701 18.544 57.0101 18.193 57.0101 16.843H62.4101ZM51.5291 11.578H57.1451C57.0911 9.499 56.7131 9.256 54.3371 9.256C52.3391 9.256 51.7181 9.526 51.5291 11.578Z"/>
<path d="M72.911 9.526C70.13 9.526 69.833 9.958 69.833 13.9C69.833 17.842 70.13 18.274 72.911 18.274C75.692 18.274 75.989 17.842 75.989 13.9C75.989 9.958 75.692 9.526 72.911 9.526ZM64.433 13.9C64.433 7.15 66.134 5.476 72.911 5.476C79.688 5.476 81.389 7.15 81.389 13.9C81.389 20.65 79.688 22.324 72.911 22.324C66.134 22.324 64.433 20.65 64.433 13.9Z"/>
<path d="M91.7698 22.324C84.9928 22.324 83.2918 20.65 83.2918 13.9C83.2918 7.15 84.9928 5.476 91.7698 5.476C98.1418 5.476 99.7888 6.907 99.9508 12.604H94.5508C94.4428 9.823 94.1728 9.526 91.7698 9.526C88.9888 9.526 88.6918 9.958 88.6918 13.9C88.6918 17.842 88.9888 18.274 91.7698 18.274C94.1458 18.274 94.4158 17.95 94.5508 15.142H99.9508C99.8158 20.893 98.1688 22.324 91.7698 22.324Z"/>
<path d="M125.562 22H120.432V19.462C119.946 21.433 118.488 22.324 115.815 22.324C111.549 22.324 110.496 21.109 110.496 16.276L110.469 5.8H115.599V15.061C115.599 17.707 115.842 18.004 118.002 18.004C119.676 18.004 120.405 17.167 120.405 15.169L120.432 5.8H125.562V22Z"/>
<path d="M128.543 0.400002H133.673V7.987C134.267 6.232 135.995 5.476 139.073 5.476C143.906 5.476 145.121 7.15 145.121 13.9C145.121 20.65 143.852 22.324 138.803 22.324C135.644 22.324 133.997 21.19 133.538 18.625V22H128.543V0.400002ZM133.673 16.276C133.673 17.491 134.78 18.004 136.643 18.004C139.424 18.004 139.721 17.599 139.721 13.9C139.721 10.201 139.451 9.796 136.94 9.796C134.645 9.796 133.673 10.714 133.673 12.874V16.276Z"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M104.167 0.500002H102.5V21.9998H104.167V21.1038H105.833V22H107.5V0.500162H105.833V1.39601H104.167V0.500002ZM104.167 3.18729V4.979H105.833V3.18729H104.167ZM104.167 8.56363V6.77028H105.833V8.56363H104.167ZM104.167 10.3549V12.1455H105.833V10.3549H104.167ZM104.167 15.729V13.9368H105.833V15.729H104.167ZM104.167 17.5203V19.3126H105.833V17.5203H104.167Z"/>
</svg>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="sidebar p-4 d-flex flex-column justify-content-between" data-dark-mode-target="sidebar">
  <div class="w-100">
    <figure class="mb-5" >
      <%= render "shared/logo" %>
    </figure>
    <ul class="mt-3 p-0 links">
      <li class="nav-item <%= active_class(root_path) %>">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fa-solid fa-ticket me-2"></i> Home
        <% end %>
      </li>
      <li class="nav-item <%= active_class(movies_path) %>">
        <%= link_to movies_path, class: "nav-link" do %>
          <i class="fa-solid fa-clapperboard me-2"></i> Movies
        <% end %>
      </li>
      <li class="nav-item <%= active_class(favorites_path) %>">
        <%= link_to favorites_path, class: "nav-link" do %>
          <i class="fa-solid fa-heart me-2"></i> Favorites
        <% end %>
      </li>
      <li class="nav-item <%= active_class(watched_movies_path) %>">
        <%= link_to watched_movies_path, class: "nav-link" do %>
          <i class="fa-solid fa-eye me-2"></i> Watched
        <% end %>
      </li>
      <li class="nav-item <%= active_class(watch_later_index_path) %>">
        <%= link_to watch_later_index_path, class: "nav-link" do %>
          <i class="fa-regular fa-clock me-2"></i> Watch Later
        <% end %>
      </li>
      <li class="nav-item <%= active_class(chatrooms_path) %>">
        <%= link_to chatrooms_path, class: "nav-link" do %>
          <i class="fa-solid fa-message me-2"></i> Messages
        <% end %>
      </li>
    </ul>
    <hr>
    <div data-controller="insert-in-the-list-sidebar">
      <h3 class="mt-4">Recent lists</h3>
      <ul class="list-unstyled mt-4 align-self-center" data-insert-in-the-list-sidebar-target="items">
        <% lists.each do |list| %>
          <%= render "shared/sidebar_item", list: list %>
        <% end %>
      </ul>
      <div data-controller="display-form">
        <button class="btn btn-primary mt-3 w-100 rounded-xl" data-action="click->display-form#toggle" data-display-form-target="button">
          <i class="fa-solid fa-plus me-2"></i> Create list
        </button>
        <div>
          <%= simple_form_for(list, html: { data: {
                insert_in_the_list_sidebar_target: 'form',
                action: "submit->insert-in-the-list-sidebar#send"
              } } ) do |f| %>
            <div data-display-form-target="form" class="d-none d-flex align-items-start gap-1">
              <%= f.input :name, placeholder: "List name", label: false, class: "col-8" %>
              <%= f.button :submit, "Create", class: "btn btn-primary col-4" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex w-100 align-items-center justify-content-between">
    <div class="d-flex align-items-center">
    <ul class="navbar-nav profile-menu d-flex flex-nowrap profile me-2">
      <li class="nav-item dropdown">
        <a class="nav-link me-1" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          <%= image_tag "avatar.png", class: "avatar", alt: "dropdown menu", height: 40, width: 40 %>
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="#"><i class="fas fa-sliders-h fa-fw"></i> Account</a></li>
          <%= link_to user_lists_path, class: "dropdown-item" do %>
            <li><i class="fas fa-list fa-fw"></i> Lists</li>
          <% end %>
          <li><hr class="dropdown-divider"></li>
          <li>
            <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" do %>
              <i class="fas fa-sign-out-alt fa-fw"></i> Log out
            <% end %></a></li>
      </ul>
    </li>
  </ul>
  <div class="d-flex flex-column">
    <small class=""><%= current_user.username %></small>
  </div>
  </div>
  <%= render "shared/dark_mode_toggle" %>
</div>
</div>

app/views/shared/_sidebar_item.html.erb
<li class="d-flex align-items-center m-2 padding">
  <%= link_to list_path(list), class: "d-flex align-items-center justify-content-between nav-link  w-100" do %>
    <div class="d-flex align-items-center">
      <% if list.movies.sample.nil? %>
        <img class="list-thumbnail me-2 img-list" src="https://image.tmdb.org/t/p/w1280/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg" alt="">
      <% else %>
        <img class="list-thumbnail me-2" src="<%= list.movies.sample.poster_url %>" alt="">
      <% end %>
      <p class="m-0"><%= list.name %></p>
    </div>
    <% if list.movies.count > 0 %>
      <div class="movie-count">
        <p><%= list.movies.count %></p>
      </div>
      <% end %>
  <% end %>
</li>